apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kustom-ai-gateway
resources:
  - ../../base
  - backend-ollama.yaml
patches:
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: HTTPRoute
      name: mock-llm
    patch: |-
      - op: replace
        path: /spec/rules/0/backendRefs/0/name
        value: ollama
